name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Test
        run: go test ./... -cover

  style: 
    name: Style
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4

     - name: Setup Go
       uses: actions/setup-go@v4
       with:
         go-version: '1.22'

     - name: Format
       run: test -z $(go fmt ./...)

     - name: Install staticcheck
       run: go install honnef.co/go/tools/cmd/staticcheck@latest
     - name: staticcheck
       run: staticcheck ./...
